apiVersion: v1 
kind: Pod 
metadata: 
  name: app-sgx 
  labels: 
    app: app-sgx 
spec: 
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - Standard_DC1s_v2
  restartPolicy: Never 
  containers: 
  - name: app-sgx 
    image: banne01/convert:mpcpython-sgx
    volumeMounts: 
    - name: dev-sgx 
      mountPath: /dev/sgx/enclave 
    securityContext: 
      privileged: true 
    ports: 
    - containerPort: 4996 
      name: http 
      protocol: TCP 
  volumes: 
  - name: dev-sgx 
    hostPath: 
      path: /dev/sgx/enclave 
      type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: python-webapi-for-serv
spec:
  type: LoadBalancer
  ports:
  - port: 4996
  selector:
    app: python-sgx
